version: '3.8'

services:
    database:
        container_name: database
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: symfony_bdd
            MYSQL_USER: symfony_user
            MYSQL_PASSWORD: symfony_pass
        ports:
            - '4306:3306'
        volumes:
            - ./docker/mysql:/var/lib/mysql

    php:
        container_name: php
        build:
            context: ./docker/php
            args:
                GIT_USER_EMAIL: 'test@test.com'
                GIT_USER_NAME: 'test'
        volumes:
            - ./:/var/www/project:rw
        depends_on:
            - database

    web_server:
        container_name: web_server
        image: nginx:stable-alpine
        environment:
            SERVER_NAME: "localhost"
        ports:
            - '8080:80'
            # for https
            - '443:443'
        volumes:
            # symfony's path project
            - ./:/var/www/project:rw
            # Nginx's config
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            # Nginx's logs
            - ./docker/nginx/logs:/var/log/nginx/
            # Nginx's https certificate ( update the default.conf if https is used)
            - ./docker/nginx/certs:/etc/nginx/ssl:rw
        depends_on:
            - php
            - database
            
